env_name: 'Ant-v4'
act_type: 'ReLU'
n_steps: 1e6
g: 0.99
lm: 0.95
u_epi_ups: 0
bs: 2048
n_itrs: 10
n_slices: 16
lr: 0.0001
h_dim: 16
u_adv_scl: 1
clip_eps: 0.2
ob_norm: 0
rew_norm: 0
use_cbp: true
rr: 1e-4
mt: 10000
util_type_val: 'contribution'
util_type_pol: 'contribution'
use_redo: false
rf: 0.0
rt: 0.0
beta_1: 0.99
beta_2: 0.99
wd: 1e-4
dir: 'data/ant/cbp/'
to_log: []
label: 'CBP'